frr version 8.4_git
frr defaults traditional
hostname p3-mpls
no ipv6 forwarding
!
interface eth1
 ip address 172.16.5.2/30
 ip ospf network point-to-point
 mpls
exit
!
interface eth2
 ip address 172.16.7.1/30
 ip ospf network point-to-point
 mpls
exit
!
interface eth3
 ip address 172.16.8.1/30
 ip ospf network point-to-point
 mpls
exit
!
interface eth4
 ip address 172.16.3.2/30
 ip ospf network point-to-point
 mpls
exit
!
interface lo
 ip address 10.0.0.23/32
 ipv6 address fd00::23/128
 mpls
exit
!
router ospf
 ospf router-id 10.0.0.23
 network 10.0.0.23/32 area 0
 network 172.16.3.0/30 area 0
 network 172.16.5.0/30 area 0
 network 172.16.7.0/30 area 0
 network 172.16.8.0/30 area 0
 capability opaque
 segment-routing on
 segment-routing node-msd 8
 segment-routing prefix 10.0.0.23/32 index 23
 router-info area
exit
!
mpls ldp
 router-id 10.0.0.23
 !
 address-family ipv4
  discovery transport-address 10.0.0.23
  !
  interface eth1
  exit
  !
  interface eth2
  exit
  !
  interface eth3
  exit
  !
  interface eth4
  exit
  !
 exit-address-family
 !
exit
!
