frr version 10.5.1_git
frr defaults traditional
hostname p1-mpls
no ipv6 forwarding
!
interface eth1
 ip address 172.16.1.2/30
 ip ospf network point-to-point
exit
!
interface eth2
 ip address 172.16.2.1/30
 ip ospf network point-to-point
exit
!
interface eth3
 ip address 172.16.5.1/30
 ip ospf network point-to-point
exit
!
interface eth4
 ip address 172.16.4.1/30
 ip ospf network point-to-point
exit
!
interface lo
 ip address 10.0.0.21/32
 ipv6 address fd00::21/128
exit
!
router bgp 65000
 bgp router-id 10.0.0.21
 no bgp ebgp-requires-policy
 no bgp enforce-first-as
 no bgp default ipv4-unicast
 bgp cluster-id 10.0.0.21
 neighbor RR-CLIENTS peer-group
 neighbor RR-CLIENTS remote-as 65000
 neighbor RR-CLIENTS update-source lo
 neighbor 10.0.0.1 peer-group RR-CLIENTS
 neighbor 10.0.0.2 peer-group RR-CLIENTS
 neighbor 10.0.0.3 peer-group RR-CLIENTS
 neighbor 10.0.0.4 peer-group RR-CLIENTS
 neighbor 10.0.0.22 remote-as 65000
 neighbor 10.0.0.22 update-source lo
 !
 address-family ipv4 vpn
  neighbor RR-CLIENTS activate
  neighbor RR-CLIENTS route-reflector-client
  neighbor 10.0.0.22 activate
 exit-address-family
exit
!
router ospf
 ospf router-id 10.0.0.21
 network 10.0.0.21/32 area 0
 network 172.16.1.0/30 area 0
 network 172.16.2.0/30 area 0
 network 172.16.4.0/30 area 0
 network 172.16.5.0/30 area 0
 capability opaque
 segment-routing on
 segment-routing global-block 16000 23900
 segment-routing node-msd 8
 segment-routing prefix 10.0.0.21/32 index 21
 router-info area
exit
!
mpls ldp
 router-id 10.0.0.21
 !
 address-family ipv4
  discovery transport-address 10.0.0.21
  !
  interface eth1
  exit
  !
  interface eth2
  exit
  !
  interface eth3
  exit
  !
  interface eth4
  exit
  !
 exit-address-family
 !
exit
!
