frr version 10.5.1_git
frr defaults traditional
hostname p2-mpls
no ipv6 forwarding
!
interface eth1
 ip address 172.16.9.2/30
 ip ospf network point-to-point
exit
!
interface eth2
 ip address 172.16.2.2/30
 ip ospf network point-to-point
exit
!
interface eth3
 ip address 172.16.6.1/30
 ip ospf network point-to-point
exit
!
interface eth4
 ip address 172.16.3.1/30
 ip ospf network point-to-point
exit
!
interface lo
 ip address 10.0.0.22/32
 ipv6 address fd00::22/128
exit
!
router bgp 65000
 bgp router-id 10.0.0.22
 no bgp ebgp-requires-policy
 no bgp enforce-first-as
 no bgp default ipv4-unicast
 bgp cluster-id 10.0.0.22
 neighbor RR-CLIENTS peer-group
 neighbor RR-CLIENTS remote-as 65000
 neighbor RR-CLIENTS update-source lo
 neighbor 10.0.0.1 peer-group RR-CLIENTS
 neighbor 10.0.0.2 peer-group RR-CLIENTS
 neighbor 10.0.0.3 peer-group RR-CLIENTS
 neighbor 10.0.0.4 peer-group RR-CLIENTS
 neighbor 10.0.0.21 remote-as 65000
 neighbor 10.0.0.21 update-source lo
 !
 address-family ipv4 vpn
  neighbor RR-CLIENTS activate
  neighbor RR-CLIENTS route-reflector-client
  neighbor 10.0.0.21 activate
 exit-address-family
exit
!
router ospf
 ospf router-id 10.0.0.22
 network 10.0.0.22/32 area 0
 network 172.16.2.0/30 area 0
 network 172.16.3.0/30 area 0
 network 172.16.6.0/30 area 0
 network 172.16.9.0/30 area 0
 capability opaque
 segment-routing on
 segment-routing node-msd 8
 segment-routing prefix 10.0.0.22/32 index 22
 router-info area
exit
!
mpls ldp
 router-id 10.0.0.22
 !
 address-family ipv4
  discovery transport-address 10.0.0.22
  !
  interface eth1
  exit
  !
  interface eth2
  exit
  !
  interface eth3
  exit
  !
  interface eth4
  exit
  !
 exit-address-family
 !
exit
!
