frr version 8.4_git
frr defaults traditional
hostname pe1-right
!
vrf CUSTOMER-A
 vni 100
exit-vrf
!
vrf CUSTOMER-B
 vni 200
exit-vrf
!
interface eth4
 ip address 192.168.1.1/30
 mpls
exit
!
interface eth5
 ip address 192.168.2.1/30
 mpls
exit
!
interface eth1
 ipv6 address 2001:db8:8::1/64
 ipv6 router isis SRv6
 isis hello-multiplier 3
 isis network point-to-point
 mpls
exit
!
interface eth2
 ip address 172.16.8.2/30
 ip ospf network point-to-point
 mpls
exit
!
interface lo
 ip address 10.0.0.3/32
 ipv6 address fd00::3/128
 ipv6 router isis SRv6
 isis passive
 mpls
exit
!
router bgp 65000
 bgp router-id 10.0.0.3
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor RR peer-group
 neighbor RR remote-as 65000
 neighbor RR update-source lo
 neighbor 10.0.0.21 peer-group RR
 neighbor 10.0.0.22 peer-group RR
 !
 address-family ipv4 vpn
  neighbor RR activate
 exit-address-family
exit
!
router bgp 65000 vrf CUSTOMER-A
 bgp router-id 10.0.0.3
 !
 address-family ipv4 unicast
  redistribute connected
  label vpn export auto
  rd vpn export 65000:100
  rt vpn both 65000:100
  export vpn
  import vpn
 exit-address-family
exit
!
router bgp 65000 vrf CUSTOMER-B
 bgp router-id 10.0.0.3
 !
 address-family ipv4 unicast
  redistribute connected
  label vpn export auto
  rd vpn export 65000:200
  rt vpn both 65000:200
  export vpn
  import vpn
 exit-address-family
exit
!
router ospf
 ospf router-id 10.0.0.3
 network 10.0.0.3/32 area 0
 network 172.16.8.0/30 area 0
 capability opaque
 segment-routing on
 segment-routing node-msd 8
 segment-routing prefix 10.0.0.3/32 index 3
 router-info area
exit
!
mpls ldp
 router-id 10.0.0.3
 !
 address-family ipv4
  discovery transport-address 10.0.0.3
  !
  interface eth2
  exit
  !
 exit-address-family
 !
exit
!
router isis SRv6
 is-type level-2-only
 net 49.0001.0000.0000.0003.00
 topology ipv6-unicast
 segment-routing on
 segment-routing node-msd 8
exit
!
segment-routing
 srv6
  locators
   locator MAIN
    prefix fd00:3::/48
   exit
   !
  exit
  !
 exit
 !
 traffic-eng
 exit
exit
!
