frr version 10.2.1_git
frr defaults traditional
hostname p2-srv6
!
interface eth1
 ipv6 address 2001:db8:9::2/64
 ipv6 router isis SRv6
 isis hello-multiplier 3
 isis network point-to-point
exit
!
interface eth2
 ipv6 address 2001:db8:2::2/64
 ipv6 router isis SRv6
 isis hello-multiplier 3
 isis network point-to-point
exit
!
interface eth3
 ipv6 address 2001:db8:6::1/64
 ipv6 router isis SRv6
 isis hello-multiplier 3
 isis network point-to-point
exit
!
interface eth4
 ipv6 address 2001:db8:3::1/64
 ipv6 router isis SRv6
 isis hello-multiplier 3
 isis network point-to-point
exit
!
interface lo
 ip address 10.0.0.12/32
 ipv6 address fd00::12/128
 ipv6 router isis SRv6
 isis passive
exit
!
router bgp 65000
 bgp router-id 10.0.0.12
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp cluster-id 10.0.0.12
 neighbor SRv6-CLIENTS peer-group
 neighbor SRv6-CLIENTS remote-as 65000
 neighbor SRv6-CLIENTS update-source lo
 neighbor SRv6-CLIENTS capability extended-nexthop
 neighbor fd00::2 peer-group SRv6-CLIENTS
 neighbor fd00::4 peer-group SRv6-CLIENTS
 neighbor fd00::11 remote-as 65000
 neighbor fd00::11 update-source lo
 neighbor fd00::11 capability extended-nexthop
 !
 segment-routing srv6
  locator MAIN
 exit
 !
 address-family ipv4 vpn
  neighbor SRv6-CLIENTS activate
  neighbor SRv6-CLIENTS route-reflector-client
  neighbor fd00::11 activate
 exit-address-family
 !
 address-family ipv6 vpn
  neighbor SRv6-CLIENTS activate
  neighbor SRv6-CLIENTS route-reflector-client
  neighbor fd00::11 activate
 exit-address-family
exit
!
router isis SRv6
 is-type level-2-only
 net 49.0001.0000.0000.0012.00
 topology ipv6-unicast
 segment-routing on
 segment-routing node-msd 8
 segment-routing srv6
  locator MAIN
 exit
exit
!
segment-routing
 srv6
  locators
   locator MAIN
    prefix fd00:12::/48 block-len 24 node-len 24 func-bits 16
   exit
   !
  exit
  !
  formats
   format usid-f3216
   exit
   !
   format uncompressed-f4024
   exit
   !
  exit
  !
 exit
 !
 traffic-eng
 exit
exit
!
